### ISSUE TITLE
ClassNotFoundException with PersistentMySQL in Tomcat 8.5 (tomcat-dbcp 7.x dependency)

### ISSUE THREAD

**Issue by ggrandes** [ggrandes/tinyurl#6]
```java
java.lang.ClassNotFoundException: org.apache.tomcat.dbcp.dbcp.BasicDataSourceFactory
        at ...
        at org.javastack.tinyurl.jdbc.DataSourceFactory.createDataSource(DataSourceFactory.java:55) ~[tinyurl-1.0.6.jar:1.0.6]
        at org.javastack.tinyurl.jdbc.PersistentMySQL.open(PersistentMySQL.java:48) ~[tinyurl-1.0.6.jar:1.0.6]
        at org.javastack.tinyurl.TinyURL.init0(TinyURL.java:154) ~[tinyurl-1.0.6.jar:1.0.6]
        at org.javastack.tinyurl.TinyURL.init(TinyURL.java:79) ~[tinyurl-1.0.6.jar:1.0.6]
        at ...
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by ggrandes** [comment]
Workaround in running environment:
Copy [tomcat-dbcp-7.0.93.jar](https://repo1.maven.org/maven2/org/apache/tomcat/tomcat-dbcp/7.0.93/tomcat-dbcp-7.0.93.jar) inside WEB-INF/lib/ of the war
